version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:8007"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thi
      - MONGO_INITDB_ROOT_PASSWORD=142536
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
